In [1]:
from pymongo import MongoClient
import pandas as pd

In [6]:
client = MongoClient("mongodb://root:rootpass@mongo:27017")

In [8]:
db = client["loja"]
produtos = db["produtos"]

In [12]:
produtos.insert_many([
{"nome":"Mouse Logitech","categoria":"Informática","preco":120,"estoque":50,"avaliacoes":[4,4,5],"disponivel":True},
{"nome":"Teclado Mecânico","categoria":"Informática","preco":350,"estoque":20,"avaliacoes":[5,5,4],"disponivel":True},
{"nome":"Smartphone Samsung","categoria":"Celulares","preco":2200,"estoque":15,"avaliacoes":[5,4,4],"disponivel":True},
{"nome":"Smartphone Xiaomi","categoria":"Celulares","preco":1800,"estoque":0,"avaliacoes":[4,4,4],"disponivel":False},
{"nome":"Fone Bluetooth","categoria":"Acessórios","preco":250,"estoque":30,"avaliacoes":[4,3,4],"disponivel":True},
{"nome":"Monitor LG","categoria":"Informática","preco":1200,"estoque":8,"avaliacoes":[5,5,5],"disponivel":True},
{"nome":"Carregador USB-C","categoria":"Acessórios","preco":80,"estoque":40,"avaliacoes":[4,4,3],"disponivel":True},
{"nome":"Tablet Lenovo","categoria":"Tablets","preco":1500,"estoque":5,"avaliacoes":[4,5,4],"disponivel":True},
{"nome":"Smartwatch Xiaomi","categoria":"Wearables","preco":900,"estoque":12,"avaliacoes":[4,4,5],"disponivel":True}
])

InsertManyResult([ObjectId('69b363230736c3add962b2e3'), ObjectId('69b363230736c3add962b2e4'), ObjectId('69b363230736c3add962b2e5'), ObjectId('69b363230736c3add962b2e6'), ObjectId('69b363230736c3add962b2e7'), ObjectId('69b363230736c3add962b2e8'), ObjectId('69b363230736c3add962b2e9'), ObjectId('69b363230736c3add962b2ea'), ObjectId('69b363230736c3add962b2eb')], acknowledged=True)

In [15]:
for item in produtos.find({"preco" : {"$gt" : 500}}):
    print(item)

{'_id': ObjectId('69b363230736c3add962b2e5'), 'nome': 'Smartphone Samsung', 'categoria': 'Celulares', 'preco': 2200, 'estoque': 15, 'avaliacoes': [5, 4, 4], 'disponivel': True}
{'_id': ObjectId('69b363230736c3add962b2e6'), 'nome': 'Smartphone Xiaomi', 'categoria': 'Celulares', 'preco': 1800, 'estoque': 0, 'avaliacoes': [4, 4, 4], 'disponivel': False}
{'_id': ObjectId('69b363230736c3add962b2e8'), 'nome': 'Monitor LG', 'categoria': 'Informática', 'preco': 1200, 'estoque': 8, 'avaliacoes': [5, 5, 5], 'disponivel': True}
{'_id': ObjectId('69b363230736c3add962b2ea'), 'nome': 'Tablet Lenovo', 'categoria': 'Tablets', 'preco': 1500, 'estoque': 5, 'avaliacoes': [4, 5, 4], 'disponivel': True}
{'_id': ObjectId('69b363230736c3add962b2eb'), 'nome': 'Smartwatch Xiaomi', 'categoria': 'Wearables', 'preco': 900, 'estoque': 12, 'avaliacoes': [4, 4, 5], 'disponivel': True}

In [17]:
dados = list(produtos.find())
dados

[{'_id': ObjectId('69b363230736c3add962b2e3'),
  'nome': 'Mouse Logitech',
  'categoria': 'Informática',
  'preco': 120,
  'estoque': 50,
  'avaliacoes': [4, 4, 5],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2e4'),
  'nome': 'Teclado Mecânico',
  'categoria': 'Informática',
  'preco': 350,
  'estoque': 20,
  'avaliacoes': [5, 5, 4],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2e5'),
  'nome': 'Smartphone Samsung',
  'categoria': 'Celulares',
  'preco': 2200,
  'estoque': 15,
  'avaliacoes': [5, 4, 4],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2e6'),
  'nome': 'Smartphone Xiaomi',
  'categoria': 'Celulares',
  'preco': 1800,
  'estoque': 0,
  'avaliacoes': [4, 4, 4],
  'disponivel': False},
 {'_id': ObjectId('69b363230736c3add962b2e7'),
  'nome': 'Fone Bluetooth',
  'categoria': 'Acessórios',
  'preco': 250,
  'estoque': 30,
  'avaliacoes': [4, 3, 4],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2e8'),
  'nome': 'Monitor LG',
  'categoria': 'Informática',
  'preco': 1200,
  'estoque': 8,
  'avaliacoes': [5, 5, 5],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2e9'),
  'nome': 'Carregador USB-C',
  'categoria': 'Acessórios',
  'preco': 80,
  'estoque': 40,
  'avaliacoes': [4, 4, 3],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2ea'),
  'nome': 'Tablet Lenovo',
  'categoria': 'Tablets',
  'preco': 1500,
  'estoque': 5,
  'avaliacoes': [4, 5, 4],
  'disponivel': True},
 {'_id': ObjectId('69b363230736c3add962b2eb'),
  'nome': 'Smartwatch Xiaomi',
  'categoria': 'Wearables',
  'preco': 900,
  'estoque': 12,
  'avaliacoes': [4, 4, 5],
  'disponivel': True}]

In [18]:
df_produtos = pd.DataFrame(dados)
df_produtos.head()

,_id,nome,categoria,preco,estoque,avaliacoes,disponivel
0,69b363230736c3add962b2e3,Mouse Logitech,Informática,120,50,"[4, 4, 5]",True
1,69b363230736c3add962b2e4,Teclado Mecânico,Informática,350,20,"[5, 5, 4]",True
2,69b363230736c3add962b2e5,Smartphone Samsung,Celulares,2200,15,"[5, 4, 4]",True
3,69b363230736c3add962b2e6,Smartphone Xiaomi,Celulares,1800,0,"[4, 4, 4]",False
4,69b363230736c3add962b2e7,Fone Bluetooth,Acessórios,250,30,"[4, 3, 4]",True

In [19]:
df_produtos = df_produtos.drop(columns=["_id"])
df_produtos.head(3)

                 nome    categoria  preco  estoque avaliacoes  disponivel
0      Mouse Logitech  Informática    120       50  [4, 4, 5]        True
1    Teclado Mecânico  Informática    350       20  [5, 5, 4]        True
2  Smartphone Samsung    Celulares   2200       15  [5, 4, 4]        True

In [21]:
df_produtos["media_avaliacoes"] = df_produtos["avaliacoes"].apply(lambda x : sum(x)/len(x))
df_produtos.head(3)

,nome,categoria,preco,estoque,avaliacoes,disponivel,media_avaliacoes
0,Mouse Logitech,Informática,120,50,"[4, 4, 5]",True,4.333333
1,Teclado Mecânico,Informática,350,20,"[5, 5, 4]",True,4.666667
2,Smartphone Samsung,Celulares,2200,15,"[5, 4, 4]",True,4.333333

lambda fez com que criasse a variável chamada "X" e guardar as informações do "avaliacoes" nesta variável, e depois pediu para somar todos os vetores e dividir pelo tamanho dos vetores

In [24]:
produtos_p = db["produtos_processados"]

In [25]:
dados_p = df_produtos.to_dict("records")
dados_p

[{'nome': 'Mouse Logitech',
  'categoria': 'Informática',
  'preco': 120,
  'estoque': 50,
  'avaliacoes': [4, 4, 5],
  'disponivel': True,
  'media_avaliacoes': 4.333333333333333},
 {'nome': 'Teclado Mecânico',
  'categoria': 'Informática',
  'preco': 350,
  'estoque': 20,
  'avaliacoes': [5, 5, 4],
  'disponivel': True,
  'media_avaliacoes': 4.666666666666667},
 {'nome': 'Smartphone Samsung',
  'categoria': 'Celulares',
  'preco': 2200,
  'estoque': 15,
  'avaliacoes': [5, 4, 4],
  'disponivel': True,
  'media_avaliacoes': 4.333333333333333},
 {'nome': 'Smartphone Xiaomi',
  'categoria': 'Celulares',
  'preco': 1800,
  'estoque': 0,
  'avaliacoes': [4, 4, 4],
  'disponivel': False,
  'media_avaliacoes': 4.0},
 {'nome': 'Fone Bluetooth',
  'categoria': 'Acessórios',
  'preco': 250,
  'estoque': 30,
  'avaliacoes': [4, 3, 4],
  'disponivel': True,
  'media_avaliacoes': 3.6666666666666665},
 {'nome': 'Monitor LG',
  'categoria': 'Informática',
  'preco': 1200,
  'estoque': 8,
  'avaliacoes': [5, 5, 5],
  'disponivel': True,
  'media_avaliacoes': 5.0},
 {'nome': 'Carregador USB-C',
  'categoria': 'Acessórios',
  'preco': 80,
  'estoque': 40,
  'avaliacoes': [4, 4, 3],
  'disponivel': True,
  'media_avaliacoes': 3.6666666666666665},
 {'nome': 'Tablet Lenovo',
  'categoria': 'Tablets',
  'preco': 1500,
  'estoque': 5,
  'avaliacoes': [4, 5, 4],
  'disponivel': True,
  'media_avaliacoes': 4.333333333333333},
 {'nome': 'Smartwatch Xiaomi',
  'categoria': 'Wearables',
  'preco': 900,
  'estoque': 12,
  'avaliacoes': [4, 4, 5],
  'disponivel': True,
  'media_avaliacoes': 4.333333333333333}]

In [26]:
produtos_p.insert_many(dados_p)

InsertManyResult([ObjectId('69b36ada0736c3add962b2ec'), ObjectId('69b36ada0736c3add962b2ed'), ObjectId('69b36ada0736c3add962b2ee'), ObjectId('69b36ada0736c3add962b2ef'), ObjectId('69b36ada0736c3add962b2f0'), ObjectId('69b36ada0736c3add962b2f1'), ObjectId('69b36ada0736c3add962b2f2'), ObjectId('69b36ada0736c3add962b2f3'), ObjectId('69b36ada0736c3add962b2f4')], acknowledged=True)

In [27]:
for item in produtos_p.find():
    print(item)

{'_id': ObjectId('69b36ada0736c3add962b2ec'), 'nome': 'Mouse Logitech', 'categoria': 'Informática', 'preco': 120, 'estoque': 50, 'avaliacoes': [4, 4, 5], 'disponivel': True, 'media_avaliacoes': 4.333333333333333}
{'_id': ObjectId('69b36ada0736c3add962b2ed'), 'nome': 'Teclado Mecânico', 'categoria': 'Informática', 'preco': 350, 'estoque': 20, 'avaliacoes': [5, 5, 4], 'disponivel': True, 'media_avaliacoes': 4.666666666666667}
{'_id': ObjectId('69b36ada0736c3add962b2ee'), 'nome': 'Smartphone Samsung', 'categoria': 'Celulares', 'preco': 2200, 'estoque': 15, 'avaliacoes': [5, 4, 4], 'disponivel': True, 'media_avaliacoes': 4.333333333333333}
{'_id': ObjectId('69b36ada0736c3add962b2ef'), 'nome': 'Smartphone Xiaomi', 'categoria': 'Celulares', 'preco': 1800, 'estoque': 0, 'avaliacoes': [4, 4, 4], 'disponivel': False, 'media_avaliacoes': 4.0}
{'_id': ObjectId('69b36ada0736c3add962b2f0'), 'nome': 'Fone Bluetooth', 'categoria': 'Acessórios', 'preco': 250, 'estoque': 30, 'avaliacoes': [4, 3, 4], 'disponivel': True, 'media_avaliacoes': 3.6666666666666665}
{'_id': ObjectId('69b36ada0736c3add962b2f1'), 'nome': 'Monitor LG', 'categoria': 'Informática', 'preco': 1200, 'estoque': 8, 'avaliacoes': [5, 5, 5], 'disponivel': True, 'media_avaliacoes': 5.0}
{'_id': ObjectId('69b36ada0736c3add962b2f2'), 'nome': 'Carregador USB-C', 'categoria': 'Acessórios', 'preco': 80, 'estoque': 40, 'avaliacoes': [4, 4, 3], 'disponivel': True, 'media_avaliacoes': 3.6666666666666665}
{'_id': ObjectId('69b36ada0736c3add962b2f3'), 'nome': 'Tablet Lenovo', 'categoria': 'Tablets', 'preco': 1500, 'estoque': 5, 'avaliacoes': [4, 5, 4], 'disponivel': True, 'media_avaliacoes': 4.333333333333333}
{'_id': ObjectId('69b36ada0736c3add962b2f4'), 'nome': 'Smartwatch Xiaomi', 'categoria': 'Wearables', 'preco': 900, 'estoque': 12, 'avaliacoes': [4, 4, 5], 'disponivel': True, 'media_avaliacoes': 4.333333333333333}